In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
Response=pd.read_csv('Career Guidance.csv')

In [3]:
Response.iloc[:,8:]

Which field  you're interested in?  Enter your 10th percentage:  \
0               Andriod(App Developer)                        80.00   
1                          Programming                        88.00   
2               Andriod(App Developer)                        93.00   
3                          Programming                        82.00   
4                        Web Developer                        62.00   
5               Andriod(App Developer)                        87.00   
6               Andriod(App Developer)                        70.00   
7                          Programming                        97.00   
8                          Programming                        78.00   
9              Networking and Hardware                        80.00   
10                         Programming                        82.00   
11                         Programming                        83.00   
12             Networking and Hardware                        80.00   
13              Andriod(App Developer)                        73.00   
14                        Data Science                        88.00   
15             Networking and Hardware                        85.00   
16                         Programming                        93.00   
17                         Programming                        98.00   
18                         Programming                        87.00   
19                       Web Developer                        75.00   
20                         Programming                        83.00   
21              Andriod(App Developer)                        77.00   
22                         Programming                        95.00   
23                         Programming                        85.00   
24                         Programming                        83.00   
25                         Programming                        82.00   
26                         Programming                        80.00   
27                         Programming                        82.00   
28              Andriod(App Developer)                        83.00   
29             Networking and Hardware                        78.00   
..                                 ...                          ...   
210                      Web Developer                        80.00   
211                      Web Developer                        60.00   
212                      Web Developer                        87.00   
213             Andriod(App Developer)                        75.00   
214             Andriod(App Developer)                        85.00   
215                      Web Developer                        93.00   
216                      Web Developer                        80.80   
217            Networking and Hardware                        82.00   
218            Networking and Hardware                        75.00   
219                      Web Developer                        70.00   
220                        Programming                        85.00   
221                        Programming                        92.00   
222                        Programming                        71.25   
223                        Programming                        63.00   
224                      Web Developer                        82.00   
225                        Programming                        55.00   
226                        Programming                        77.00   
227             Andriod(App Developer)                        80.00   
228                        Programming                        88.50   
229             Andriod(App Developer)                        77.00   
230                        Programming                        80.00   
231                      Web Developer                        95.00   
232                        Programming                        83.00   
233                        Programming                        80.00   
234            Networking an

In [4]:
d=Response.iloc[:,8:]
label = Response.iloc[:,8].values

In [5]:
d.iloc[0,4]

'd.C & C++ & Java'

In [6]:
    for i in range(0,240):
        for j in range(4,6):
            wh=d.iloc[i,j]

            if wh[0]=='a':
                d.iloc[i,j]=0
            elif wh[0]=='b':
                d.iloc[i,j]=10
            elif wh[0]=='c':
                d.iloc[i,j]=15
            elif wh[0]=='d':
                d.iloc[i,j]=25



In [7]:
d

Which field  you're interested in?  Enter your 10th percentage:  \
0               Andriod(App Developer)                        80.00   
1                          Programming                        88.00   
2               Andriod(App Developer)                        93.00   
3                          Programming                        82.00   
4                        Web Developer                        62.00   
5               Andriod(App Developer)                        87.00   
6               Andriod(App Developer)                        70.00   
7                          Programming                        97.00   
8                          Programming                        78.00   
9              Networking and Hardware                        80.00   
10                         Programming                        82.00   
11                         Programming                        83.00   
12             Networking and Hardware                        80.00   
13              Andriod(App Developer)                        73.00   
14                        Data Science                        88.00   
15             Networking and Hardware                        85.00   
16                         Programming                        93.00   
17                         Programming                        98.00   
18                         Programming                        87.00   
19                       Web Developer                        75.00   
20                         Programming                        83.00   
21              Andriod(App Developer)                        77.00   
22                         Programming                        95.00   
23                         Programming                        85.00   
24                         Programming                        83.00   
25                         Programming                        82.00   
26                         Programming                        80.00   
27                         Programming                        82.00   
28              Andriod(App Developer)                        83.00   
29             Networking and Hardware                        78.00   
..                                 ...                          ...   
210                      Web Developer                        80.00   
211                      Web Developer                        60.00   
212                      Web Developer                        87.00   
213             Andriod(App Developer)                        75.00   
214             Andriod(App Developer)                        85.00   
215                      Web Developer                        93.00   
216                      Web Developer                        80.80   
217            Networking and Hardware                        82.00   
218            Networking and Hardware                        75.00   
219                      Web Developer                        70.00   
220                        Programming                        85.00   
221                        Programming                        92.00   
222                        Programming                        71.25   
223                        Programming                        63.00   
224                      Web Developer                        82.00   
225                        Programming                        55.00   
226                        Programming                        77.00   
227             Andriod(App Developer)                        80.00   
228                        Programming                        88.50   
229             Andriod(App Developer)                        77.00   
230                        Programming                        80.00   
231                      Web Developer                        95.00   
232                        Programming                        83.00   
233                        Programming                        80.00   
234            Networking an

In [8]:
for i in range(0,240):
    for j in range(6,8):
        where=d.iloc[i,j]
        if d.iloc[i,j]=='nan':
            d.iloc[i,j]=0
            
        elif where[0]=='d':
            d.iloc[i,j]=25
        else:
            d.iloc[i,j]=0
        


In [9]:
d

Which field  you're interested in?  Enter your 10th percentage:  \
0               Andriod(App Developer)                        80.00   
1                          Programming                        88.00   
2               Andriod(App Developer)                        93.00   
3                          Programming                        82.00   
4                        Web Developer                        62.00   
5               Andriod(App Developer)                        87.00   
6               Andriod(App Developer)                        70.00   
7                          Programming                        97.00   
8                          Programming                        78.00   
9              Networking and Hardware                        80.00   
10                         Programming                        82.00   
11                         Programming                        83.00   
12             Networking and Hardware                        80.00   
13              Andriod(App Developer)                        73.00   
14                        Data Science                        88.00   
15             Networking and Hardware                        85.00   
16                         Programming                        93.00   
17                         Programming                        98.00   
18                         Programming                        87.00   
19                       Web Developer                        75.00   
20                         Programming                        83.00   
21              Andriod(App Developer)                        77.00   
22                         Programming                        95.00   
23                         Programming                        85.00   
24                         Programming                        83.00   
25                         Programming                        82.00   
26                         Programming                        80.00   
27                         Programming                        82.00   
28              Andriod(App Developer)                        83.00   
29             Networking and Hardware                        78.00   
..                                 ...                          ...   
210                      Web Developer                        80.00   
211                      Web Developer                        60.00   
212                      Web Developer                        87.00   
213             Andriod(App Developer)                        75.00   
214             Andriod(App Developer)                        85.00   
215                      Web Developer                        93.00   
216                      Web Developer                        80.80   
217            Networking and Hardware                        82.00   
218            Networking and Hardware                        75.00   
219                      Web Developer                        70.00   
220                        Programming                        85.00   
221                        Programming                        92.00   
222                        Programming                        71.25   
223                        Programming                        63.00   
224                      Web Developer                        82.00   
225                        Programming                        55.00   
226                        Programming                        77.00   
227             Andriod(App Developer)                        80.00   
228                        Programming                        88.50   
229             Andriod(App Developer)                        77.00   
230                        Programming                        80.00   
231                      Web Developer                        95.00   
232                        Programming                        83.00   
233                        Programming                        80.00   
234            Networking an

In [10]:
for i in range(0,240):
    for j in range(8,10):
        where=d.iloc[i,j]
        
        if where[0]=='a':
            d.iloc[i,j]=0
        elif where[0]=='b':
            d.iloc[i,j]=10
        elif where[0]=='c':
            d.iloc[i,j]=15
        elif where[0]=='d':
            d.iloc[i,j]=25



In [11]:
d

Which field  you're interested in?  Enter your 10th percentage:  \
0               Andriod(App Developer)                        80.00   
1                          Programming                        88.00   
2               Andriod(App Developer)                        93.00   
3                          Programming                        82.00   
4                        Web Developer                        62.00   
5               Andriod(App Developer)                        87.00   
6               Andriod(App Developer)                        70.00   
7                          Programming                        97.00   
8                          Programming                        78.00   
9              Networking and Hardware                        80.00   
10                         Programming                        82.00   
11                         Programming                        83.00   
12             Networking and Hardware                        80.00   
13              Andriod(App Developer)                        73.00   
14                        Data Science                        88.00   
15             Networking and Hardware                        85.00   
16                         Programming                        93.00   
17                         Programming                        98.00   
18                         Programming                        87.00   
19                       Web Developer                        75.00   
20                         Programming                        83.00   
21              Andriod(App Developer)                        77.00   
22                         Programming                        95.00   
23                         Programming                        85.00   
24                         Programming                        83.00   
25                         Programming                        82.00   
26                         Programming                        80.00   
27                         Programming                        82.00   
28              Andriod(App Developer)                        83.00   
29             Networking and Hardware                        78.00   
..                                 ...                          ...   
210                      Web Developer                        80.00   
211                      Web Developer                        60.00   
212                      Web Developer                        87.00   
213             Andriod(App Developer)                        75.00   
214             Andriod(App Developer)                        85.00   
215                      Web Developer                        93.00   
216                      Web Developer                        80.80   
217            Networking and Hardware                        82.00   
218            Networking and Hardware                        75.00   
219                      Web Developer                        70.00   
220                        Programming                        85.00   
221                        Programming                        92.00   
222                        Programming                        71.25   
223                        Programming                        63.00   
224                      Web Developer                        82.00   
225                        Programming                        55.00   
226                        Programming                        77.00   
227             Andriod(App Developer)                        80.00   
228                        Programming                        88.50   
229             Andriod(App Developer)                        77.00   
230                        Programming                        80.00   
231                      Web Developer                        95.00   
232                        Programming                        83.00   
233                        Programming                        80.00   
234            Networking an

In [12]:
for i in range(0,240):
    for j in range(10,12):
        where=d.iloc[i,j]
        
        if where[0]=='d':
            d.iloc[i,j]=25
        else:
            d.iloc[i,j]=0
        


In [13]:
d

Which field  you're interested in?  Enter your 10th percentage:  \
0               Andriod(App Developer)                        80.00   
1                          Programming                        88.00   
2               Andriod(App Developer)                        93.00   
3                          Programming                        82.00   
4                        Web Developer                        62.00   
5               Andriod(App Developer)                        87.00   
6               Andriod(App Developer)                        70.00   
7                          Programming                        97.00   
8                          Programming                        78.00   
9              Networking and Hardware                        80.00   
10                         Programming                        82.00   
11                         Programming                        83.00   
12             Networking and Hardware                        80.00   
13              Andriod(App Developer)                        73.00   
14                        Data Science                        88.00   
15             Networking and Hardware                        85.00   
16                         Programming                        93.00   
17                         Programming                        98.00   
18                         Programming                        87.00   
19                       Web Developer                        75.00   
20                         Programming                        83.00   
21              Andriod(App Developer)                        77.00   
22                         Programming                        95.00   
23                         Programming                        85.00   
24                         Programming                        83.00   
25                         Programming                        82.00   
26                         Programming                        80.00   
27                         Programming                        82.00   
28              Andriod(App Developer)                        83.00   
29             Networking and Hardware                        78.00   
..                                 ...                          ...   
210                      Web Developer                        80.00   
211                      Web Developer                        60.00   
212                      Web Developer                        87.00   
213             Andriod(App Developer)                        75.00   
214             Andriod(App Developer)                        85.00   
215                      Web Developer                        93.00   
216                      Web Developer                        80.80   
217            Networking and Hardware                        82.00   
218            Networking and Hardware                        75.00   
219                      Web Developer                        70.00   
220                        Programming                        85.00   
221                        Programming                        92.00   
222                        Programming                        71.25   
223                        Programming                        63.00   
224                      Web Developer                        82.00   
225                        Programming                        55.00   
226                        Programming                        77.00   
227             Andriod(App Developer)                        80.00   
228                        Programming                        88.50   
229             Andriod(App Developer)                        77.00   
230                        Programming                        80.00   
231                      Web Developer                        95.00   
232                        Programming                        83.00   
233                        Programming                        80.00   
234            Networking an

In [14]:
for i in range(0,240):
    for j in range(12,14):
        where=d.iloc[i,j]
        
        if where[0]=='a':
            d.iloc[i,j]=0
        elif where[0]=='b':
            d.iloc[i,j]=10
        elif where[0]=='c':
            d.iloc[i,j]=15
        elif where[0]=='d':
            d.iloc[i,j]=25



In [15]:
d

Which field  you're interested in?  Enter your 10th percentage:  \
0               Andriod(App Developer)                        80.00   
1                          Programming                        88.00   
2               Andriod(App Developer)                        93.00   
3                          Programming                        82.00   
4                        Web Developer                        62.00   
5               Andriod(App Developer)                        87.00   
6               Andriod(App Developer)                        70.00   
7                          Programming                        97.00   
8                          Programming                        78.00   
9              Networking and Hardware                        80.00   
10                         Programming                        82.00   
11                         Programming                        83.00   
12             Networking and Hardware                        80.00   
13              Andriod(App Developer)                        73.00   
14                        Data Science                        88.00   
15             Networking and Hardware                        85.00   
16                         Programming                        93.00   
17                         Programming                        98.00   
18                         Programming                        87.00   
19                       Web Developer                        75.00   
20                         Programming                        83.00   
21              Andriod(App Developer)                        77.00   
22                         Programming                        95.00   
23                         Programming                        85.00   
24                         Programming                        83.00   
25                         Programming                        82.00   
26                         Programming                        80.00   
27                         Programming                        82.00   
28              Andriod(App Developer)                        83.00   
29             Networking and Hardware                        78.00   
..                                 ...                          ...   
210                      Web Developer                        80.00   
211                      Web Developer                        60.00   
212                      Web Developer                        87.00   
213             Andriod(App Developer)                        75.00   
214             Andriod(App Developer)                        85.00   
215                      Web Developer                        93.00   
216                      Web Developer                        80.80   
217            Networking and Hardware                        82.00   
218            Networking and Hardware                        75.00   
219                      Web Developer                        70.00   
220                        Programming                        85.00   
221                        Programming                        92.00   
222                        Programming                        71.25   
223                        Programming                        63.00   
224                      Web Developer                        82.00   
225                        Programming                        55.00   
226                        Programming                        77.00   
227             Andriod(App Developer)                        80.00   
228                        Programming                        88.50   
229             Andriod(App Developer)                        77.00   
230                        Programming                        80.00   
231                      Web Developer                        95.00   
232                        Programming                        83.00   
233                        Programming                        80.00   
234            Networking an

In [16]:
for i in range(0,240):
    for j in range(14,16):
        where=d.iloc[i,j]
        if d.iloc[i,j]=='nan':
            d.iloc[i,j]=0
            
        elif where[0]=='d':
            d.iloc[i,j]=25
        else:
            d.iloc[i,j]=0
        


In [17]:
d

Which field  you're interested in?  Enter your 10th percentage:  \
0               Andriod(App Developer)                        80.00   
1                          Programming                        88.00   
2               Andriod(App Developer)                        93.00   
3                          Programming                        82.00   
4                        Web Developer                        62.00   
5               Andriod(App Developer)                        87.00   
6               Andriod(App Developer)                        70.00   
7                          Programming                        97.00   
8                          Programming                        78.00   
9              Networking and Hardware                        80.00   
10                         Programming                        82.00   
11                         Programming                        83.00   
12             Networking and Hardware                        80.00   
13              Andriod(App Developer)                        73.00   
14                        Data Science                        88.00   
15             Networking and Hardware                        85.00   
16                         Programming                        93.00   
17                         Programming                        98.00   
18                         Programming                        87.00   
19                       Web Developer                        75.00   
20                         Programming                        83.00   
21              Andriod(App Developer)                        77.00   
22                         Programming                        95.00   
23                         Programming                        85.00   
24                         Programming                        83.00   
25                         Programming                        82.00   
26                         Programming                        80.00   
27                         Programming                        82.00   
28              Andriod(App Developer)                        83.00   
29             Networking and Hardware                        78.00   
..                                 ...                          ...   
210                      Web Developer                        80.00   
211                      Web Developer                        60.00   
212                      Web Developer                        87.00   
213             Andriod(App Developer)                        75.00   
214             Andriod(App Developer)                        85.00   
215                      Web Developer                        93.00   
216                      Web Developer                        80.80   
217            Networking and Hardware                        82.00   
218            Networking and Hardware                        75.00   
219                      Web Developer                        70.00   
220                        Programming                        85.00   
221                        Programming                        92.00   
222                        Programming                        71.25   
223                        Programming                        63.00   
224                      Web Developer                        82.00   
225                        Programming                        55.00   
226                        Programming                        77.00   
227             Andriod(App Developer)                        80.00   
228                        Programming                        88.50   
229             Andriod(App Developer)                        77.00   
230                        Programming                        80.00   
231                      Web Developer                        95.00   
232                        Programming                        83.00   
233                        Programming                        80.00   
234            Networking an

In [18]:
for i in range(0,240):
    for j in range(16,18):
        where=d.iloc[i,j]
        
        if where[0]=='a':
            d.iloc[i,j]=0
        elif where[0]=='b':
            d.iloc[i,j]=10
        elif where[0]=='c':
            d.iloc[i,j]=15
        elif where[0]=='d':
            d.iloc[i,j]=25



In [19]:
d

Which field  you're interested in?  Enter your 10th percentage:  \
0               Andriod(App Developer)                        80.00   
1                          Programming                        88.00   
2               Andriod(App Developer)                        93.00   
3                          Programming                        82.00   
4                        Web Developer                        62.00   
5               Andriod(App Developer)                        87.00   
6               Andriod(App Developer)                        70.00   
7                          Programming                        97.00   
8                          Programming                        78.00   
9              Networking and Hardware                        80.00   
10                         Programming                        82.00   
11                         Programming                        83.00   
12             Networking and Hardware                        80.00   
13              Andriod(App Developer)                        73.00   
14                        Data Science                        88.00   
15             Networking and Hardware                        85.00   
16                         Programming                        93.00   
17                         Programming                        98.00   
18                         Programming                        87.00   
19                       Web Developer                        75.00   
20                         Programming                        83.00   
21              Andriod(App Developer)                        77.00   
22                         Programming                        95.00   
23                         Programming                        85.00   
24                         Programming                        83.00   
25                         Programming                        82.00   
26                         Programming                        80.00   
27                         Programming                        82.00   
28              Andriod(App Developer)                        83.00   
29             Networking and Hardware                        78.00   
..                                 ...                          ...   
210                      Web Developer                        80.00   
211                      Web Developer                        60.00   
212                      Web Developer                        87.00   
213             Andriod(App Developer)                        75.00   
214             Andriod(App Developer)                        85.00   
215                      Web Developer                        93.00   
216                      Web Developer                        80.80   
217            Networking and Hardware                        82.00   
218            Networking and Hardware                        75.00   
219                      Web Developer                        70.00   
220                        Programming                        85.00   
221                        Programming                        92.00   
222                        Programming                        71.25   
223                        Programming                        63.00   
224                      Web Developer                        82.00   
225                        Programming                        55.00   
226                        Programming                        77.00   
227             Andriod(App Developer)                        80.00   
228                        Programming                        88.50   
229             Andriod(App Developer)                        77.00   
230                        Programming                        80.00   
231                      Web Developer                        95.00   
232                        Programming                        83.00   
233                        Programming                        80.00   
234            Networking an

In [20]:
for i in range(0,240):
    for j in range(18,20):
        where=d.iloc[i,j]
        if d.iloc[i,j]=='nan':
            d.iloc[i,j]=0
            
        elif where[0]=='d':
            d.iloc[i,j]=25
        else:
            d.iloc[i,j]=0
        


In [21]:
d

Which field  you're interested in?  Enter your 10th percentage:  \
0               Andriod(App Developer)                        80.00   
1                          Programming                        88.00   
2               Andriod(App Developer)                        93.00   
3                          Programming                        82.00   
4                        Web Developer                        62.00   
5               Andriod(App Developer)                        87.00   
6               Andriod(App Developer)                        70.00   
7                          Programming                        97.00   
8                          Programming                        78.00   
9              Networking and Hardware                        80.00   
10                         Programming                        82.00   
11                         Programming                        83.00   
12             Networking and Hardware                        80.00   
13              Andriod(App Developer)                        73.00   
14                        Data Science                        88.00   
15             Networking and Hardware                        85.00   
16                         Programming                        93.00   
17                         Programming                        98.00   
18                         Programming                        87.00   
19                       Web Developer                        75.00   
20                         Programming                        83.00   
21              Andriod(App Developer)                        77.00   
22                         Programming                        95.00   
23                         Programming                        85.00   
24                         Programming                        83.00   
25                         Programming                        82.00   
26                         Programming                        80.00   
27                         Programming                        82.00   
28              Andriod(App Developer)                        83.00   
29             Networking and Hardware                        78.00   
..                                 ...                          ...   
210                      Web Developer                        80.00   
211                      Web Developer                        60.00   
212                      Web Developer                        87.00   
213             Andriod(App Developer)                        75.00   
214             Andriod(App Developer)                        85.00   
215                      Web Developer                        93.00   
216                      Web Developer                        80.80   
217            Networking and Hardware                        82.00   
218            Networking and Hardware                        75.00   
219                      Web Developer                        70.00   
220                        Programming                        85.00   
221                        Programming                        92.00   
222                        Programming                        71.25   
223                        Programming                        63.00   
224                      Web Developer                        82.00   
225                        Programming                        55.00   
226                        Programming                        77.00   
227             Andriod(App Developer)                        80.00   
228                        Programming                        88.50   
229             Andriod(App Developer)                        77.00   
230                        Programming                        80.00   
231                      Web Developer                        95.00   
232                        Programming                        83.00   
233                        Programming                        80.00   
234            Networking an

In [22]:
for i in range(0,240):
    for j in range(20,22):
        where=d.iloc[i,j]
        
        if where[0]=='a':
            d.iloc[i,j]=0
        elif where[0]=='b':
            d.iloc[i,j]=10
        elif where[0]=='c':
            d.iloc[i,j]=15
        elif where[0]=='d':
            d.iloc[i,j]=25



In [23]:
d

Which field  you're interested in?  Enter your 10th percentage:  \
0               Andriod(App Developer)                        80.00   
1                          Programming                        88.00   
2               Andriod(App Developer)                        93.00   
3                          Programming                        82.00   
4                        Web Developer                        62.00   
5               Andriod(App Developer)                        87.00   
6               Andriod(App Developer)                        70.00   
7                          Programming                        97.00   
8                          Programming                        78.00   
9              Networking and Hardware                        80.00   
10                         Programming                        82.00   
11                         Programming                        83.00   
12             Networking and Hardware                        80.00   
13              Andriod(App Developer)                        73.00   
14                        Data Science                        88.00   
15             Networking and Hardware                        85.00   
16                         Programming                        93.00   
17                         Programming                        98.00   
18                         Programming                        87.00   
19                       Web Developer                        75.00   
20                         Programming                        83.00   
21              Andriod(App Developer)                        77.00   
22                         Programming                        95.00   
23                         Programming                        85.00   
24                         Programming                        83.00   
25                         Programming                        82.00   
26                         Programming                        80.00   
27                         Programming                        82.00   
28              Andriod(App Developer)                        83.00   
29             Networking and Hardware                        78.00   
..                                 ...                          ...   
210                      Web Developer                        80.00   
211                      Web Developer                        60.00   
212                      Web Developer                        87.00   
213             Andriod(App Developer)                        75.00   
214             Andriod(App Developer)                        85.00   
215                      Web Developer                        93.00   
216                      Web Developer                        80.80   
217            Networking and Hardware                        82.00   
218            Networking and Hardware                        75.00   
219                      Web Developer                        70.00   
220                        Programming                        85.00   
221                        Programming                        92.00   
222                        Programming                        71.25   
223                        Programming                        63.00   
224                      Web Developer                        82.00   
225                        Programming                        55.00   
226                        Programming                        77.00   
227             Andriod(App Developer)                        80.00   
228                        Programming                        88.50   
229             Andriod(App Developer)                        77.00   
230                        Programming                        80.00   
231                      Web Developer                        95.00   
232                        Programming                        83.00   
233                        Programming                        80.00   
234            Networking an

In [24]:
for i in range(0,240):
    for j in range(22,24):
        where=d.iloc[i,j]
        if d.iloc[i,j]=='nan':
            d.iloc[i,j]=0
            
        elif where[0]=='d':
            d.iloc[i,j]=25
        else:
            d.iloc[i,j]=0
        


In [25]:
d

Which field  you're interested in?  Enter your 10th percentage:  \
0               Andriod(App Developer)                        80.00   
1                          Programming                        88.00   
2               Andriod(App Developer)                        93.00   
3                          Programming                        82.00   
4                        Web Developer                        62.00   
5               Andriod(App Developer)                        87.00   
6               Andriod(App Developer)                        70.00   
7                          Programming                        97.00   
8                          Programming                        78.00   
9              Networking and Hardware                        80.00   
10                         Programming                        82.00   
11                         Programming                        83.00   
12             Networking and Hardware                        80.00   
13              Andriod(App Developer)                        73.00   
14                        Data Science                        88.00   
15             Networking and Hardware                        85.00   
16                         Programming                        93.00   
17                         Programming                        98.00   
18                         Programming                        87.00   
19                       Web Developer                        75.00   
20                         Programming                        83.00   
21              Andriod(App Developer)                        77.00   
22                         Programming                        95.00   
23                         Programming                        85.00   
24                         Programming                        83.00   
25                         Programming                        82.00   
26                         Programming                        80.00   
27                         Programming                        82.00   
28              Andriod(App Developer)                        83.00   
29             Networking and Hardware                        78.00   
..                                 ...                          ...   
210                      Web Developer                        80.00   
211                      Web Developer                        60.00   
212                      Web Developer                        87.00   
213             Andriod(App Developer)                        75.00   
214             Andriod(App Developer)                        85.00   
215                      Web Developer                        93.00   
216                      Web Developer                        80.80   
217            Networking and Hardware                        82.00   
218            Networking and Hardware                        75.00   
219                      Web Developer                        70.00   
220                        Programming                        85.00   
221                        Programming                        92.00   
222                        Programming                        71.25   
223                        Programming                        63.00   
224                      Web Developer                        82.00   
225                        Programming                        55.00   
226                        Programming                        77.00   
227             Andriod(App Developer)                        80.00   
228                        Programming                        88.50   
229             Andriod(App Developer)                        77.00   
230                        Programming                        80.00   
231                      Web Developer                        95.00   
232                        Programming                        83.00   
233                        Programming                        80.00   
234            Networking an

In [26]:
ds=d.iloc[:,:9]
ds

Which field  you're interested in?  Enter your 10th percentage:  \
0               Andriod(App Developer)                        80.00   
1                          Programming                        88.00   
2               Andriod(App Developer)                        93.00   
3                          Programming                        82.00   
4                        Web Developer                        62.00   
5               Andriod(App Developer)                        87.00   
6               Andriod(App Developer)                        70.00   
7                          Programming                        97.00   
8                          Programming                        78.00   
9              Networking and Hardware                        80.00   
10                         Programming                        82.00   
11                         Programming                        83.00   
12             Networking and Hardware                        80.00   
13              Andriod(App Developer)                        73.00   
14                        Data Science                        88.00   
15             Networking and Hardware                        85.00   
16                         Programming                        93.00   
17                         Programming                        98.00   
18                         Programming                        87.00   
19                       Web Developer                        75.00   
20                         Programming                        83.00   
21              Andriod(App Developer)                        77.00   
22                         Programming                        95.00   
23                         Programming                        85.00   
24                         Programming                        83.00   
25                         Programming                        82.00   
26                         Programming                        80.00   
27                         Programming                        82.00   
28              Andriod(App Developer)                        83.00   
29             Networking and Hardware                        78.00   
..                                 ...                          ...   
210                      Web Developer                        80.00   
211                      Web Developer                        60.00   
212                      Web Developer                        87.00   
213             Andriod(App Developer)                        75.00   
214             Andriod(App Developer)                        85.00   
215                      Web Developer                        93.00   
216                      Web Developer                        80.80   
217            Networking and Hardware                        82.00   
218            Networking and Hardware                        75.00   
219                      Web Developer                        70.00   
220                        Programming                        85.00   
221                        Programming                        92.00   
222                        Programming                        71.25   
223                        Programming                        63.00   
224                      Web Developer                        82.00   
225                        Programming                        55.00   
226                        Programming                        77.00   
227             Andriod(App Developer)                        80.00   
228                        Programming                        88.50   
229             Andriod(App Developer)                        77.00   
230                        Programming                        80.00   
231                      Web Developer                        95.00   
232                        Programming                        83.00   
233                        Programming                        80.00   
234            Networking an

In [27]:
for i in range(0,240):
    p,q,r,s,t=0,0,0,0,0
    for j in range(4,8):
        p=p+d.iloc[i,j]
        if j==7:
            ds.iloc[i,4]=p
            break;
        else:pass
    for k in range(8,12):
        q=q+d.iloc[i,k]
        if k==11 :
            ds.iloc[i,5]=q
            break;
        else:pass
    for l in range(12,16):
        r=r+d.iloc[i,l]
        if l==15 :
            ds.iloc[i,6]=r
            break;
        else:pass
    for m in range(16,20):
        s=s+d.iloc[i,m]
        if m==19 :
            ds.iloc[i,7]=s
            break;
        else:pass
    for n in range(20,24):
        t=t+d.iloc[i,j]
        if j==23 :
            ds.iloc[i,8]=t
            break;
        else:pass

In [28]:
ds

Which field  you're interested in?  Enter your 10th percentage:  \
0               Andriod(App Developer)                        80.00   
1                          Programming                        88.00   
2               Andriod(App Developer)                        93.00   
3                          Programming                        82.00   
4                        Web Developer                        62.00   
5               Andriod(App Developer)                        87.00   
6               Andriod(App Developer)                        70.00   
7                          Programming                        97.00   
8                          Programming                        78.00   
9              Networking and Hardware                        80.00   
10                         Programming                        82.00   
11                         Programming                        83.00   
12             Networking and Hardware                        80.00   
13              Andriod(App Developer)                        73.00   
14                        Data Science                        88.00   
15             Networking and Hardware                        85.00   
16                         Programming                        93.00   
17                         Programming                        98.00   
18                         Programming                        87.00   
19                       Web Developer                        75.00   
20                         Programming                        83.00   
21              Andriod(App Developer)                        77.00   
22                         Programming                        95.00   
23                         Programming                        85.00   
24                         Programming                        83.00   
25                         Programming                        82.00   
26                         Programming                        80.00   
27                         Programming                        82.00   
28              Andriod(App Developer)                        83.00   
29             Networking and Hardware                        78.00   
..                                 ...                          ...   
210                      Web Developer                        80.00   
211                      Web Developer                        60.00   
212                      Web Developer                        87.00   
213             Andriod(App Developer)                        75.00   
214             Andriod(App Developer)                        85.00   
215                      Web Developer                        93.00   
216                      Web Developer                        80.80   
217            Networking and Hardware                        82.00   
218            Networking and Hardware                        75.00   
219                      Web Developer                        70.00   
220                        Programming                        85.00   
221                        Programming                        92.00   
222                        Programming                        71.25   
223                        Programming                        63.00   
224                      Web Developer                        82.00   
225                        Programming                        55.00   
226                        Programming                        77.00   
227             Andriod(App Developer)                        80.00   
228                        Programming                        88.50   
229             Andriod(App Developer)                        77.00   
230                        Programming                        80.00   
231                      Web Developer                        95.00   
232                        Programming                        83.00   
233                        Programming                        80.00   
234            Networking an

In [36]:
for i in range(0,240):
    if ds.iloc[i,0]=="Andriod(App Developer)" :
        ds.iloc[i,0]=1
    elif ds.iloc[i,0]=="Programming" :
        ds.iloc[i,0]=2
    elif ds.iloc[i,0]=="Web Developer" :
        ds.iloc[i,0]=3
    elif ds.iloc[i,0]=="Networking and Hardware" :
        ds.iloc[i,0]=4
    elif ds.iloc[i,0]=="Data Science" :
        ds.iloc[i,0]=5
    else:pass

In [237]:
ds

Which field  you're interested in?  Enter your 10th percentage:  \
0                                    1                        80.00   
1                                    2                        88.00   
2                                    1                        93.00   
3                                    2                        82.00   
4                                    3                        62.00   
5                                    1                        87.00   
6                                    1                        70.00   
7                                    2                        97.00   
8                                    2                        78.00   
9                                    4                        80.00   
10                                   2                        82.00   
11                                   2                        83.00   
12                                   4                        80.00   
13                                   1                        73.00   
14                                   5                        88.00   
15                                   4                        85.00   
16                                   2                        93.00   
17                                   2                        98.00   
18                                   2                        87.00   
19                                   3                        75.00   
20                                   2                        83.00   
21                                   1                        77.00   
22                                   2                        95.00   
23                                   2                        85.00   
24                                   2                        83.00   
25                                   2                        82.00   
26                                   2                        80.00   
27                                   2                        82.00   
28                                   1                        83.00   
29                                   4                        78.00   
..                                 ...                          ...   
210                                  3                        80.00   
211                                  3                        60.00   
212                                  3                        87.00   
213                                  1                        75.00   
214                                  1                        85.00   
215                                  3                        93.00   
216                                  3                        80.80   
217                                  4                        82.00   
218                                  4                        75.00   
219                                  3                        70.00   
220                                  2                        85.00   
221                                  2                        92.00   
222                                  2                        71.25   
223                                  2                        63.00   
224                                  3                        82.00   
225                                  2                        55.00   
226                                  2                        77.00   
227                                  1                        80.00   
228                                  2                        88.50   
229                                  1                        77.00   
230                                  2                        80.00   
231                                  3                        95.00   
232                                  2                        83.00   
233                                  2                        80.00   
234                         

In [37]:
dataset=pd.DataFrame(data=d)
dataset.to_csv('career_marks.csv')
dataset=pd.read_csv('career_marks.csv')
dataset

Unnamed: 0  Which field  you're interested in?  \
0             0                                   1   
1             1                                   2   
2             2                                   1   
3             3                                   2   
4             4                                   3   
5             5                                   1   
6             6                                   1   
7             7                                   2   
8             8                                   2   
9             9                                   4   
10           10                                   2   
11           11                                   2   
12           12                                   4   
13           13                                   1   
14           14                                   5   
15           15                                   4   
16           16                                   2   
17           17                                   2   
18           18                                   2   
19           19                                   3   
20           20                                   2   
21           21                                   1   
22           22                                   2   
23           23                                   2   
24           24                                   2   
25           25                                   2   
26           26                                   2   
27           27                                   2   
28           28                                   1   
29           29                                   4   
..          ...                                 ...   
210         210                                   3   
211         211                                   3   
212         212                                   3   
213         213                                   1   
214         214                                   1   
215         215                                   3   
216         216                                   3   
217         217                                   4   
218         218                                   4   
219         219                                   3   
220         220                                   2   
221         221                                   2   
222         222                                   2   
223         223                                   2   
224         224                                   3   
225         225                                   2   
226         226                                   2   
227         227                                   1   
228         228                                   2   
229         229                                   1   
230         230                                   2   
231         231                                   3   
232         232                                   2   
233         233                                   2   
234         234                                   4   
235         235                                   5   
236         236                                   4   
237         237                                   4   
238         238                                   2   
239         239                                   1   

     Enter your 10th percentage:  Enter your 12th/diploma  percentage:  \
0                          80.00                                  85.0   
1                          88.00                                  95.7   
2                          93.00                                  98.0   
3                          82.00                                  92.0   
4                          62.00                                  96.0   
5                          87.00                                  92.0   
6                          70.00                                  90.4   
7 

In [238]:
from sklearn.preprocessing import Normalizer

In [239]:
normalized_data = Normalizer().fit_transform(ds)
print(normalized_data.shape)

(240, 9)


In [240]:
normalized_data

array([[0.00676495, 0.54119569, 0.57502042, ..., 0.16912365, 0.16912365,
        0.10147419],
       [0.01134269, 0.49907853, 0.5427479 , ..., 0.19849714, 0.14178367,
        0.        ],
       [0.0052933 , 0.49227715, 0.51874366, ..., 0.29113165, 0.13233257,
        0.        ],
       ...,
       [0.03119578, 0.35095255, 0.38994727, ..., 0.11698418, 0.38994727,
        0.07798945],
       [0.01228503, 0.55282647, 0.48403029, ..., 0.09213774, 0.        ,
        0.15356291],
       [0.005881  , 0.45924729, 0.5169399 , ..., 0.17643   , 0.147025  ,
        0.088215  ]])

In [241]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()

In [242]:
X1 = pd.DataFrame(normalized_data,columns=[
        "Which field you're interested in?",
        "Enter your 10th percentage:",
        "Enter your 12th/diploma percentage",
        "Enter your present percentage (Till date):",
       '1.programming',
       '2.web designing',
       '3.networking',
       '4.data science',
       '5.android',
      ])

In [243]:
columns=X1.columns
columns

Index(['Which field you're interested in?', 'Enter your 10th percentage:',
       'Enter your 12th/diploma percentage',
       'Enter your present percentage (Till date):', '1.programming',
       '2.web designing', '3.networking', '4.data science', '5.android'],
      dtype='object')

In [244]:
X1.head()

Which field you're interested in?  Enter your 10th percentage:  \
0                           0.006765                     0.541196   
1                           0.011343                     0.499079   
2                           0.005293                     0.492277   
3                           0.011629                     0.476793   
4                           0.020875                     0.431420   

   Enter your 12th/diploma percentage  \
0                            0.575020   
1                            0.542748   
2                            0.518744   
3                            0.534938   
4                            0.668005   

   Enter your present percentage (Till date):  1.programming  2.web designing  \
0                                    0.473546       0.236773         0.169124   
1                                    0.442365       0.425351         0.141784   
2                                    0.428758       0.449931         0.000000   
3                                    0.470978       0.348873         0.000000   
4                                    0.501004       0.243543         0.104376   

   3.networking  4.data science  5.android  
0      0.169124        0.169124   0.101474  
1      0.198497        0.141784   0.000000  
2      0.291132        0.132333   0.000000  
3      0.348873        0.145364   0.000000  
4      0.173960        0.069584   0.104376

In [245]:
label = labelencoder.fit_transform(label)
print(len(label))

240


In [246]:
k = labelencoder.fit_transform(label)
print(len(label))

240


In [247]:
y=pd.DataFrame(label,columns=["Suggested Job Role"])
y.head()

Suggested Job Role
0                   0
1                   3
2                   0
3                   3
4                   4

In [248]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import preprocessing 
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix,accuracy_score

In [274]:
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.10,random_state=10)

In [275]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [276]:
y_pred = clf.predict(X_test)

In [277]:
y_pred

array([0, 3, 3, 3, 3, 4, 4, 2, 1, 3, 3, 4, 4, 3, 4, 3, 3, 3, 4, 0, 0, 3,
       3, 0], dtype=int64)

In [278]:
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)

In [279]:
print("confusion matrics=",cm)
print("  ")
print("accuracy=",accuracy*100)

confusion matrics= [[ 4  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  1  1  0  2]
 [ 0  0  0 12  0]
 [ 0  0  0  0  4]]
  
accuracy= 87.5


In [286]:
clf_entropy = tree.DecisionTreeClassifier(criterion = "entropy", random_state =15)
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=15, splitter='best')

In [287]:
entropy_y_pred=clf_entropy.predict(X_test)

In [288]:
cm_entopy = confusion_matrix(y_test,entropy_y_pred)

In [289]:
entropy_accuracy = accuracy_score(y_test,entropy_y_pred)

In [290]:
print("confusion matrics=",cm_entopy)
print("  ")
print("accuracy=",entropy_accuracy*100)

confusion matrics= [[ 4  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  1  0  0  3]
 [ 0  0  0 12  0]
 [ 0  0  0  0  4]]
  
accuracy= 83.33333333333334


In [291]:
from sklearn import svm
clf = svm.SVC()
clf.fit(X_train, y_train)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [292]:
from sklearn import svm

In [293]:
svm_y_pred = clf.predict(X_test)

In [294]:
svm_cm = confusion_matrix(y_test,svm_y_pred)
svm_accuracy = accuracy_score(y_test,svm_y_pred)

In [295]:
print("confusion matrics=",svm_cm)
print("  ")
print("accuracy=",svm_accuracy*100)

confusion matrics= [[ 0  0  4  0]
 [ 0  0  4  0]
 [ 0  0 12  0]
 [ 0  0  4  0]]
  
accuracy= 50.0


In [304]:
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.20,random_state=10)
X_train.shape

(192, 9)

In [305]:
X_train=pd.to_numeric(X_train.values.flatten())

In [306]:
X_train=X_train.reshape((192,9))

In [307]:
from xgboost import XGBClassifier

In [308]:
model = XGBClassifier()
model.fit(X_train, y_train)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:112: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:147: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [309]:
xgb_y_pred = clf.predict(X_test)

In [310]:
xgb_cm = confusion_matrix(y_test,xgb_y_pred)
xgb_accuracy = accuracy_score(y_test,xgb_y_pred)


In [311]:
print("confusion matrics=",xgb_cm)
print("  ")
print("accuracy=",xgb_accuracy*100)

confusion matrics= [[ 0  0  0 10  0]
 [ 0  0  0  1  0]
 [ 0  0  0  5  0]
 [ 0  0  0 21  0]
 [ 0  0  0 11  0]]
  
accuracy= 43.75


In [35]:
#K Means Implementation in Python.

# Importing Modules
#from sklearn.cluster import KMeans

# Declaring Model
#model = KMeans(n_clusters=5)

# Fitting Model
#model.fit(x1)

# Prediction on the entire data
#all_predictions = model.predict(x1)

# Printing Predictions
#print(all_predictions)

